### ISSUE TITLE
Installation not working via devtools in RStudio

### ISSUE THREAD

**Issue by Stacey-Koornneef** [jeromefroe/circlepackeR#6]
When I input the following command,
devtools::install_github("jeromefroe/circlepackeR")
 into RStudio's console tool, I get the following result:

Downloading GitHub repo jeromefroe/circlepackeR@master
from URL https://api.github.com/repos/jeromefroe/circlepackeR/zipball/master
Installing circlepackeR
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Stacey's Laptop/AppData/Local/Temp/RtmpsnXRoy/devtools4dc44952287d/jeromefroe-circlepackeR-f0a84d5"  \
  --library="C:/Users/Stacey's Laptop/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'circlepackeR' ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'circlepackeR'
    finding HTML links ... done
    circlepackeR                            html  
    circlepackeROutput                      html  
    renderCirclepackeR                      html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error: unexpected symbol in "tools:::.test_load_package('circlepackeR', 'C:/Users/Stacey's"
Execution halted
*** arch - x64
Error: unexpected symbol in "tools:::.test_load_package('circlepackeR', 'C:/Users/Stacey's"
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Stacey's Laptop/Documents/R/win-library/3.5/circlepackeR'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by jeromefroe** [comment]
Hey, this appears to be an issue with the `devtools` package, [it doesn't support installing into directories which contain an apostrophe](https://github.com/r-lib/devtools/issues/1114). The easiest thing would probably be to rename the directory `Stacey's Laptop` to remove the apostrophe.
